apiVersion: v1
kind: Service
metadata:
  name: jupiter-service
  labels:
        app: jupiter-app
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  - port: 8081
    targetPort: 8081
    name: management
  selector:
    app: jupiter-app
  type: LoadBalancer
