apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupiter-deployment
  labels:
      app: jupiter-app
spec:
  selector:
    matchLabels:
      app: jupiter-app
  replicas: 1
  template:
    metadata:
      labels:
        app: jupiter-app
    spec:
      containers:
      - name: jupiter-app
        image: pavanpaik/jupiter:0.1
        ports:
        - containerPort: 8080
          name: server
        - containerPort: 8081
          name: management
